/**
 * API Compatibility Integration Tests
 * 
 * These tests verify compatibility between frontend and backend API formats,
 * ensuring the new standardized ApiResponse format works correctly with
 * real backend endpoints.
 * 
 * Requirements: 6.5 - Integration testing for new API format
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import type { ApiResponse, Category, MenuItem, PaginatedResult } from '~/types';
import { 
  createMockSuccessResponse, 
  createMockErrorResponse, 
  createMockPaginatedResponse,
  createMockAuthError,
  createMockValidationError,
  createMockTenantError
} from '../factories/api-response.factory';

describe('API Compatibility Integration Tests', () => {
  let originalFetch: typeof global.fetch;

  beforeEach(() => {
    // Store and mock fetch for each test
    originalFetch = global.fetch;
    global.fetch = vi.fn();
  });

  afterEach(() => {
    // Restore original fetch
    global.fetch = originalFetch;
  });

  describe('🔄 Backend API Response Format Validation', () => {
    it('should validate standard ApiResponse structure from backend', async () => {
      // Test that our type guards correctly identify valid ApiResponse
      const validResponse: ApiResponse<string[]> = {
        success: true,
        statusCode: 200,
        data: ['item1', 'item2'],
        error: null,
        meta: {
          requestId: 'req-123',
          timestamp: '2023-12-20T10:00:00Z',
          tenantId: 'test-tenant'
        }
      };

      const { isApiResponse } = await import('~/utils/type-guards');
      
      expect(isApiResponse(validResponse)).toBe(true);
      expect(validResponse.success).toBe(true);
      expect(validResponse.data).toEqual(['item1', 'item2']);
      expect(validResponse.meta.requestId).toBe('req-123');
    });

    it('should detect legacy response format', async () => {
      // Test legacy format detection
      const legacyResponse = {
        items: ['item1', 'item2'],
        total: 2,
        page: 1
      };

      const { isLegacyResponse } = await import('~/utils/type-guards');
      
      expect(isLegacyResponse(legacyResponse)).toBe(true);
    });

    it('should normalize legacy responses to standard format', async () => {
      const legacyResponse = {
        items: [{ id: '1', name: 'Test Item' }],
        total: 1,
        page: 1,
        limit: 20
      };

      const { normalizeResponse } = await import('~/utils/response-normalizer');
      
      const normalized = normalizeResponse(legacyResponse, 200, '/test-endpoint');
      
      expect(normalized.success).toBe(true);
      expect(normalized.statusCode).toBe(200);
      expect(normalized.data).toEqual(legacyResponse);
      expect(normalized.meta).toHaveProperty('requestId');
      expect(normalized.meta).toHaveProperty('timestamp');
    });
  });

  describe('🌐 Real API Endpoint Testing', () => {
    const tenantSlug = 'vkusnaya-pizza';

    it('should handle menu categories endpoint correctly', async () => {
      // Mock backend response for categories
      const backendResponse = createMockSuccessResponse([
        { id: '1', name: 'Pizza', itemCount: 5 },
        { id: '2', name: 'Beverages', itemCount: 3 }
      ], {
        statusCode: 200,
        requestId: 'categories-test-123',
        tenantId: tenantSlug
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        status: 200,
        json: async () => backendResponse,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      const { MenuService } = await import('~/services/menu.service');
      const menuService = new MenuService(apiClient);
      
      const categories = await menuService.getCategories();
      
      // Verify service correctly processes backend response
      expect(categories).toBeDefined();
      expect(Array.isArray(categories)).toBe(true);
      expect(categories).toHaveLength(2);
      
      // Verify transformation from backend format to frontend format
      expect(categories[0]).toHaveProperty('id', '1');
      expect(categories[0]).toHaveProperty('name', 'Pizza');
      expect(categories[0]).toHaveProperty('count', 5);
      expect(categories[0]).toHaveProperty('icon'); // Added by service
      expect(categories[0]).toHaveProperty('description'); // Generated by service
    });

    it('should handle menu items endpoint with pagination', async () => {
      // Mock backend response for menu items
      const backendMenus = [{
        id: 'menu-1',
        items: [
          {
            id: 'item-1',
            name: 'Margherita Pizza',
            description: 'Classic pizza',
            price: 250,
            imageUrl: '/pizza.jpg',
            isActive: true,
            category: { id: '1', name: 'Pizza' },
            calories: 800,
            cookingTime: 15,
            dietary: ['vegetarian']
          }
        ]
      }];

      const backendResponse = createMockSuccessResponse(backendMenus, {
        statusCode: 200,
        requestId: 'menu-items-test-456',
        tenantId: tenantSlug,
        pagination: {
          page: 1,
          limit: 20,
          totalItems: 1,
          totalPages: 1
        }
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        status: 200,
        json: async () => backendResponse,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      const { MenuService } = await import('~/services/menu.service');
      const menuService = new MenuService(apiClient);
      
      const result = await menuService.getMenuItems({ page: 1, limit: 20 });
      
      // Verify service returns PaginatedResult format
      expect(result).toHaveProperty('items');
      expect(result).toHaveProperty('pagination');
      expect(result.items).toHaveLength(1);
      expect(result.pagination).toEqual({
        page: 1,
        limit: 20,
        totalItems: 1,
        totalPages: 1
      });
      
      // Verify item structure
      const item = result.items[0];
      expect(item).toHaveProperty('id', 'item-1');
      expect(item).toHaveProperty('name', 'Margherita Pizza');
      expect(item).toHaveProperty('price', 250);
      expect(item).toHaveProperty('categoryId', '1');
    });

    it('should handle authentication endpoints correctly', async () => {
      // Mock login response
      const loginResponse = createMockSuccessResponse({
        accessToken: 'jwt-token-123',
        refreshToken: 'refresh-token-456',
        user: {
          id: 'user-1',
          email: 'test@example.com',
          firstName: 'Test',
          lastName: 'User'
        }
      }, {
        statusCode: 200,
        requestId: 'login-test-789'
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        status: 200,
        json: async () => loginResponse,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      const result = await apiClient.post('/auth/login', {
        email: 'test@example.com',
        password: 'password123'
      });
      
      // Verify unwrapped authentication data
      expect(result).toHaveProperty('accessToken', 'jwt-token-123');
      expect(result).toHaveProperty('refreshToken', 'refresh-token-456');
      expect(result).toHaveProperty('user');
      expect(result.user).toHaveProperty('email', 'test@example.com');
    });
  });

  describe('❌ Error Response Compatibility', () => {
    it('should handle validation errors from backend', async () => {
      // Mock backend validation error
      const validationError = createMockValidationError({
        email: 'Email is required',
        password: 'Password must be at least 8 characters',
        firstName: 'First name is required'
      }, {
        statusCode: 422,
        requestId: 'validation-error-123'
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: false,
        status: 422,
        json: async () => validationError,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      try {
        await apiClient.post('/auth/register', {
          email: '',
          password: '123',
          firstName: ''
        });
        
        expect.fail('Expected validation error to be thrown');
      } catch (error: any) {
        // Verify error structure matches backend format
        expect(error).toHaveProperty('code', 'VALIDATION_ERROR');
        expect(error).toHaveProperty('message', 'Validation failed');
        expect(error).toHaveProperty('details');
        expect(Array.isArray(error.details)).toBe(true);
        expect(error.details).toHaveLength(3);
        
        // Verify field-specific errors
        const emailError = error.details.find((d: any) => d.field === 'email');
        expect(emailError).toHaveProperty('message', 'Email is required');
        
        // Verify metadata
        expect(error).toHaveProperty('requestId', 'validation-error-123');
      }
    });

    it('should handle authentication errors from backend', async () => {
      // Mock backend auth error
      const authError = createMockAuthError({
        code: 'AUTHENTICATION_ERROR',
        message: 'Invalid credentials',
        statusCode: 401,
        requestId: 'auth-error-456'
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: false,
        status: 401,
        json: async () => authError,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      try {
        await apiClient.post('/auth/login', {
          email: 'test@example.com',
          password: 'wrongpassword'
        });
        
        expect.fail('Expected authentication error to be thrown');
      } catch (error: any) {
        expect(error).toHaveProperty('code', 'AUTHENTICATION_ERROR');
        expect(error).toHaveProperty('message', 'Invalid credentials');
        expect(error).toHaveProperty('requestId', 'auth-error-456');
      }
    });

    it('should handle tenant-specific errors from backend', async () => {
      // Mock tenant error
      const tenantError = createMockTenantError('TENANT_NOT_FOUND', 'nonexistent-tenant', {
        message: 'Tenant not found',
        statusCode: 404,
        requestId: 'tenant-error-789'
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: false,
        status: 404,
        json: async () => tenantError,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      try {
        await apiClient.get('/public/menu/nonexistent-tenant');
        expect.fail('Expected tenant error to be thrown');
      } catch (error: any) {
        expect(error).toHaveProperty('code', 'TENANT_NOT_FOUND');
        expect(error).toHaveProperty('message', 'Tenant not found');
        expect(error).toHaveProperty('requestId', 'tenant-error-789');
      }
    });

    it('should handle server errors from backend', async () => {
      // Mock server error
      const serverError = createMockErrorResponse('SERVER_ERROR', 'Internal server error', {
        statusCode: 500,
        requestId: 'server-error-123'
      });

      (global.fetch as any).mockResolvedValue({
        ok: false,
        status: 500,
        json: async () => serverError,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      try {
        await apiClient.get('/test-endpoint');
        expect.fail('Expected server error to be thrown');
      } catch (error: any) {
        expect(error).toHaveProperty('code', 'SERVER_ERROR');
        expect(error).toHaveProperty('message', 'Internal server error');
        expect(error).toHaveProperty('requestId', 'server-error-123');
      }
    });
  });

  describe('🔄 Request/Response Flow Testing', () => {
    it('should send correct headers for tenant requests', async () => {
      const tenantSlug = 'test-tenant';
      
      // Mock successful response
      const mockResponse = createMockSuccessResponse({ success: true });
      
      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        status: 200,
        json: async () => mockResponse,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      // Set tenant and make request
      apiClient.setTenant(tenantSlug);
      await apiClient.get('/test-endpoint');
      
      // Verify fetch was called with correct headers
      expect(global.fetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          headers: expect.objectContaining({
            'X-Tenant-Slug': tenantSlug,
            'Content-Type': 'application/json'
          })
        })
      );
    });

    it('should handle bypass tenant requests correctly', async () => {
      // Mock successful response
      const mockResponse = createMockSuccessResponse({ tenants: [] });
      
      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        status: 200,
        json: async () => mockResponse,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      await apiClient.get('/admin/tenants', { bypassTenant: true });
      
      // Verify bypass header is sent
      expect(global.fetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          headers: expect.objectContaining({
            'X-Bypass-Tenant': 'true'
          })
        })
      );
    });

    it('should handle authentication headers correctly', async () => {
      // Mock token store
      const mockTokenStore = {
        accessToken: 'jwt-token-123'
      };

      // Mock successful response
      const mockResponse = createMockSuccessResponse({ data: 'protected' });
      
      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        status: 200,
        json: async () => mockResponse,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      // Set token store
      apiClient.setTokenStore(mockTokenStore);
      
      await apiClient.get('/protected-endpoint');
      
      // Verify authorization header is sent
      expect(global.fetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          headers: expect.objectContaining({
            'Authorization': 'Bearer jwt-token-123'
          })
        })
      );
    });
  });

  describe('🔄 Retry and Recovery Testing', () => {
    it('should retry on network failures', async () => {
      let callCount = 0;
      
      // Mock network failure then success
      (global.fetch as any).mockImplementation(() => {
        callCount++;
        if (callCount === 1) {
          return Promise.reject(new TypeError('Network error'));
        }
        
        return Promise.resolve({
          ok: true,
          status: 200,
          json: async () => createMockSuccessResponse({ success: true }),
          headers: new Headers({ 'content-type': 'application/json' })
        });
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      const result = await apiClient.get('/retry-endpoint', { retries: 2 });
      
      expect(callCount).toBe(2);
      expect(result).toEqual({ success: true });
    });

    it('should handle token refresh on 401 errors', async () => {
      let callCount = 0;
      const mockTokenStore = {
        accessToken: 'old-token',
        refreshToken: 'refresh-token-123',
        setTokens: vi.fn()
      };

      (global.fetch as any).mockImplementation((url: string) => {
        callCount++;
        
        // First call returns 401
        if (callCount === 1) {
          return Promise.resolve({
            ok: false,
            status: 401,
            json: async () => createMockAuthError(),
            headers: new Headers({ 'content-type': 'application/json' })
          });
        }
        
        // Token refresh call
        if (url.includes('/auth/refresh')) {
          return Promise.resolve({
            ok: true,
            status: 200,
            json: async () => createMockSuccessResponse({
              accessToken: 'new-token',
              refreshToken: 'new-refresh-token'
            }),
            headers: new Headers({ 'content-type': 'application/json' })
          });
        }
        
        // Retry with new token
        return Promise.resolve({
          ok: true,
          status: 200,
          json: async () => createMockSuccessResponse({ data: 'success' }),
          headers: new Headers({ 'content-type': 'application/json' })
        });
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      apiClient.setTokenStore(mockTokenStore);
      
      const result = await apiClient.get('/protected-endpoint');
      
      // Verify token refresh was called
      expect(mockTokenStore.setTokens).toHaveBeenCalledWith('new-token', 'new-refresh-token');
      expect(result).toEqual({ data: 'success' });
    });
  });

  describe('📊 Performance and Caching', () => {
    it('should handle large response payloads efficiently', async () => {
      // Create large mock response
      const largeData = Array.from({ length: 1000 }, (_, i) => ({
        id: `item-${i}`,
        name: `Item ${i}`,
        description: `Description for item ${i}`.repeat(10) // Make it larger
      }));

      const mockResponse = createMockPaginatedResponse(largeData, {
        page: 1,
        limit: 1000,
        totalItems: 1000,
        totalPages: 1
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        status: 200,
        json: async () => mockResponse,
        headers: new Headers({ 'content-type': 'application/json' })
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      const startTime = Date.now();
      const result = await apiClient.get('/large-dataset');
      const endTime = Date.now();
      
      // Verify response is handled efficiently (should be fast)
      expect(endTime - startTime).toBeLessThan(1000); // Less than 1 second
      expect(Array.isArray(result)).toBe(true);
      expect(result).toHaveLength(1000);
    });

    it('should handle concurrent requests correctly', async () => {
      // Mock multiple responses
      (global.fetch as any).mockImplementation((url: string) => {
        const id = url.split('/').pop();
        return Promise.resolve({
          ok: true,
          status: 200,
          json: async () => createMockSuccessResponse({ id, data: `Data for ${id}` }),
          headers: new Headers({ 'content-type': 'application/json' })
        });
      });

      const { useApiClient } = await import('~/utils/api');
      const apiClient = useApiClient();
      
      // Make concurrent requests
      const promises = Array.from({ length: 5 }, (_, i) => 
        apiClient.get(`/endpoint/${i}`)
      );
      
      const results = await Promise.all(promises);
      
      // Verify all requests completed successfully
      expect(results).toHaveLength(5);
      results.forEach((result, index) => {
        expect(result).toHaveProperty('id', index.toString());
        expect(result).toHaveProperty('data', `Data for ${index}`);
      });
    });
  });
});